### 1. Kirim Request ke API untuk Mendapatkan Menu Hari Ini
//POST http://192.168.12.184/dapur/public/api/menu-hari-ini
POST http://10.8.0.14:8001/api/menu-hari-ini

Content-Type: application/json

{
    "nomor_dapur": "tester",
    "tanggal": "2025-03-12",
    "karbohidrat": "Nasi",
    "protein": "Ayam Goreng",
    "sayur": "Lodeh",
    "buah": "Melon",
    "susu": "Susu Sapi"
}

### cek api
//GET http://127.0.0.1:8000/api/menu-hari-ini
GET http://10.8.0.14:8001/dapur/public/api/menu-hari-ini